name: Docker Build and push 
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker hub 
        uses: docker/login-action@v3
        with:
            username: ${{vars.DOCKERHUB_USER}}
            password: ${{secrets.DOCKERHUB_TOCKEN}}
      - name: build and push to docker hub 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKERHUB_USER}}/github-action-app:${{github.GITHUB_HEAD_REF}}
            ${{vars.DOCKERHUB_USER}}/github-action-app:latest
            ${{vars.DOCKERHUB_USER}}/github-action-app:${{github.GITHUB_SHA}}

            

    